
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # This itself is a server so, don't want server to connect to itself
    fetch-registry: false


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

#okta:
#  oauth2:
#    issuer: https://dev-15585796.okta.com/oauth2/default
#    audience: api://default
#spring:
#  zipkin:
#    baseUrl: http://zipkin-svc:9411
