version: '3'

services:
  serviceregistry:
    image: 'vaibhav1701/serviceregistry:latest'
    container_name: serviceregistry
    ports:
      - '8761:8761'

  configserver:
    image: 'vaibhav1701/configserver:latest'
    container_name: configserver
    ports:
      - '9296:9296'
    depends_on:
      - serviceregistry
    environment:
      - DOCKER_LOCAL_URL=host.docker.internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://configserver:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  cloudgateway:
    image: 'vaibhav1701/cloudgateway:latest'
    container_name: cloudgateway
    ports:
      - '9090:9090'
    depends_on: 
      configserver:
        condition: service_healthy
    environment:
      - DOCKER_LOCAL_URL=host.docker.internal

  order-service:
    image: 'vaibhav1701/order-service:latest'
    container_name: order-service
    ports:
      - '8082:8082'
    depends_on:
      - cloudgateway
    environment:
      - DOCKER_LOCAL_URL=host.docker.internal
      - DB_HOST=host.docker.internal

  product-service:
    image: 'vaibhav1701/product-service:latest'
    container_name: product-service
    ports:
      - '8080:8080'
    depends_on:
      - cloudgateway
    environment:
      - DOCKER_LOCAL_URL=host.docker.internal
      - DB_HOST=host.docker.internal

  payment-service:
    image: 'vaibhav1701/payment-service:latest'
    container_name: payment-service
    ports:
      - '8081:8081'
    depends_on:
      - cloudgateway
    environment:
      - DOCKER_LOCAL_URL=host.docker.internal
      - DB_HOST=host.docker.internal
